server {
    listen 80;
    server_name conectamais.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name conectamais.duckdns.org;

    # Certificados (Caminhos internos do container)
    ssl_certificate     /etc/nginx/ssl/live/conectamais.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/conectamais.duckdns.org/privkey.pem;

    # Segurança SSL
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # ── Arquivos de mídia ──────────────────────────────────────────────
    location /media/ {
        alias /var/www/media/;
        expires 7d;
        add_header Cache-Control "public, immutable";
        add_header Access-Control-Allow-Origin "*";
        client_max_body_size 50M;
    }

    # ── API Spring Boot ────────────────────────────────────────────────
    location /conecta/ {
        proxy_pass          http://api:8080/conecta/;
        proxy_http_version  1.1;
        proxy_set_header    Host               $host;
        proxy_set_header    X-Forwarded-Host   $host;
        proxy_set_header    X-Forwarded-Proto  https; # Informa ao Java que é HTTPS
        proxy_set_header    X-Forwarded-Port   443;
        proxy_set_header    X-Real-IP          $remote_addr;
        proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header    Authorization      $http_authorization;
        proxy_pass_header   Authorization;

        proxy_connect_timeout 10s;
        proxy_send_timeout    30s;
        proxy_read_timeout    30s;

        client_max_body_size 50M;
    }

    # ── Frontend Angular ───────────────────────────────────────────────
    location / {
        proxy_pass          http://ui:3000;
        proxy_http_version  1.1;
        proxy_set_header    Host               $host;
        proxy_set_header    X-Real-IP          $remote_addr;
        proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto  $scheme;
        proxy_set_header    Upgrade            $http_upgrade;
        proxy_set_header    Connection         "upgrade";

        proxy_connect_timeout 5s;
        proxy_send_timeout    15s;
        proxy_read_timeout    15s;
    }
}