package com.etec.zl.conecta.Domain.ValueObjects;

public enum Cursos {

    ADMINISTRACAO,
    CONTABILIDADE,
    DESENVOLVIMENTO_DE_SISTEMAS,
    LOGISTICA,
    SERVICOS_JURIDICOS,

    MATUTINO_ADMINISTRACAO_MTEC,
    MATUTINO_CONTABILIDADE_MTEC,
    MATUTINO_DESENVOLVIMENTO_DE_SISTEMAS_MTEC,
    MATUTINO_LOGISTICA_MTEC,
    MATUTINO_RECURSOS_HUMANOS_MTEC,

    VESPERTINO_ADMINISTRACAO_MTEC,
    VESPERTINO_CONTABILIDADE_MTEC,
    VESPERTINO_DESENVOLVIMENTO_DE_SISTEMAS_MTEC,
    VESPERTINO_LOGISTICA_MTEC,
    VESPERTINO_RECURSOS_HUMANOS_MTEC,

    LOGISTICA_MTEC_N,

    DESENVOLVIMENTO_DE_SISTEMAS_AMS
}
